### PR TITLE
Some top-level improvements (add print command)

### PR DESCRIPTION
**Pull request by jonsterling**

### CODE REVIEW

**Comment by jonsterling** [comment]
image


@cangiuli There seems to be a problem with the vim mode not correctly handling the first error? What I expect to happen is that the `print` line should be marked with an error indicator, but nothing happens. By comparison, the next error does work. (To be clear, the problem is not in showing multiple errors at once --- I only put the other error in there to demonstrate that some errors do work.)

**Comment by cangiuli** [comment]
I think what's happening is that error is being printed to stdout, and currently I am scanning stderr for Errors and stdout for Info. Since other unbound variable errors print to stderr, I suggest changing this behavior from the cooltt end, but it could also be easily fixed from the vim end.

**Comment by jonsterling** [comment]
@cangiuli Oh I see, I think this should be fixed from cooltt's end, not vim.

**Comment by jonsterling** [comment]
Thanks, that worked!

**Pull request merged**
