### PR TITLE
Make type annotations non-associative.

### PR DESCRIPTION
**Pull request by favonia**
It seems simpler to ban these useless recursive type annotations altogether.

### CODE REVIEW

**Comment by favonia** [comment]
This partially reverts #94. I guess Jon was right after all... it's difficult to control the power...

**Comment by jonsterling** [comment]
lmao 👍

**Comment by favonia** [comment]
Wait why didn't this ban all recursive type annotations? This still seems to be okay:
```
def x : nat = 2 : nat : nat : nat
```

**Comment by jonsterling** [comment]
I don't care too much, but between banning and allowing, it's just choose whatever makes the code simplest lol

**Comment by favonia** [comment]
It was the precedence which enables this.

**Pull request merged**
