### PR TITLE
Source locations

### LINKED ISSUE #17: Source locations
OK, my proposal for getting started is as follows:

1. The `ElabEnv` should have a "current span" field --- the invariant is that as you get deeper into an elaboration problem the span narrows. It is the responsibility of the elaborator to set this span correctly. This information can then be used when emitting messages or errors.

2. I guess we should annotate the concrete syntax in such a way that the elaborator has this information. One way is to add dummy nodes in the concrete syntax that annotate with source information, and then the elaborator executes these by locally updating the `ElabEnv`.

### PR DESCRIPTION
**Pull request by jonsterling**
Resolves #17

### CODE REVIEW

**Comment by jonsterling** [comment]
Shit @favonia I should have had you start from this branch LOL!

**Comment by favonia** [comment]
@jonsterling Done (?).

**Comment by jonsterling** [comment]
@Favonia Thank god!! LOL

**Comment by jonsterling** [comment]
Can you approve https://github.com/jonsterling/cooltt/pull/71?

**Comment by ivoysey** [comment]
this looks great!

**Comment by jonsterling** [comment]
@ivoysey 👍 Thanks!!

**Pull request merged**
