### PR TITLE
Use the new GitHub Action

### PR DESCRIPTION
**Pull request by favonia**

### CODE REVIEW

**Comment by favonia** [comment]
@jonsterling I bumped up the version number to 4.10.0. Only you can change the requirement, I think.

**Comment by favonia** [comment]
It seems the new CI can be done < 3 mins.

**Review by jonsterling — APPROVED** [review]
Wow, awesome! Please merge as soon as the CI is happy.

**Comment by favonia** [comment]
> Wow, awesome! Please merge as soon as the CI is happy.

Only you can change the setting :wink:

**Comment by jonsterling** [comment]
Wait, what setting do I need to change? It is currently waiting for the CI to finish.

**Comment by favonia** [comment]
> Wait, what setting do I need to change? It is currently waiting for the CI to finish.

Compiler version has been changed, and the compiler version is part of the CI name, so the rules need to be updated as well: [how to edit a branch protection rule](https://docs.github.com/en/github/administering-a-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule#editing-a-branch-protection-rule)

**Pull request merged**
