### PR TITLE
Simplify test_sequent and left_invert_under_cof.

### PR DESCRIPTION
**Pull request by favonia**
@jonsterling I want to see what would go wrong...

### CODE REVIEW

**Comment by jonsterling** [comment]
Huh, it might actually be OK after all

**Comment by favonia** [comment]
> I think I now understand why your idea was correct after all. Looks good to me!

I am not so confident LOL. In the modified code, `Cof.Join []` will just be "okayed" without triggering inconsistency.

**Comment by jonsterling** [comment]
Oh, wait, I think I misread something.

**Comment by favonia** [comment]
I think `Cof.Meet []` can definitely go away. I don't understand what `Cof.bot` should do in this function yet.

**Pull request merged**
