### PR TITLE
Some optimization of CofEnv

### PR DESCRIPTION
**Pull request by jonsterling**
Not sure if this is worth it, but I figured we could save a lookup. Does this make sense, or am I braindead?

### CODE REVIEW

**Comment by favonia** [comment]
I can't tell if it's worth it. If UF is implemented correctly, then the lookup should be almost constant, which means your pattern matching _should_ not save much. (Disclaimer: I only see how it works it my dream.)

**Comment by jonsterling** [comment]
Aha:) Well, I implemented the UF not so carefully, so I don't know for sure. I'm fine if you prefer to close this PR.

**Comment by favonia** [comment]
I remember I once implemented a wild version like this but in the UF library directly. Could not find it now. :-/

**Comment by favonia** [comment]
PS: I am neutral about this PR.

**Comment by jonsterling** [comment]
this seems useless, let me just close it for now

**Pull request closed without merging**
