### PR TITLE
🔙 Backward compatibility

### PR DESCRIPTION
**Pull request by favonia**

### CODE REVIEW

**Review by jonsterling — APPROVED** [review]
Looks good! I don’t like the keyword argument on map, but now that it is a different library I guess it is out of scope for me to complain about it here LOL :)

**Comment by favonia** [comment]
> Looks good! I don’t like the keyword argument on map, but now that it is a different library I guess it is out of scope for me to complain about it here LOL :)

But you are also one of the contributors! LOL

**Comment by favonia** [comment]
I am going to tag @TOTBWF so that there are odd numbers of people. @jonsterling By the way, is the `f` label of `Bwd.map` the only thing you do not like, or actually all the labels in `Bwd`? Currently, the `Bwd` is sort of a submodule of `ListLabels`, but we can certainly change that.

**Comment by favonia** [comment]
Actually, let me merge this first and resolve minor issues later.

**Pull request merged**
