### PR TITLE
document the theory

### PR DESCRIPTION
**Pull request by cangiuli**
interval, cofibrations, cubical subtypes

### CODE REVIEW

**Comment by jonsterling** [comment]
I just built the doc and the algorithms are gone ??

**Comment by cangiuli** [comment]
> I just built the doc and the algorithms are gone ??

Don't Worry About It (they're back, I wanted to compile faster)

**Comment by jonsterling** [comment]
I don't understand or like the `p : [phi] --> ...` thing haha. Maybe just write `phi true !- ...`, or did you want to avoid this or something?

**Comment by cangiuli** [comment]
I thought _you_ wanted to avoid it, lol!

**Comment by jonsterling** [comment]
LOL. I am OK with some Cool notation that is easy to understand

**Pull request merged**
