### PR TITLE
🚧 WIP 💤 SMT for cofibrations

### LINKED ISSUE #197: ⚙️ SMT for deciding cofibrations
The basic idea is to use SMT solvers in replace of `cubical.CofThy`. See the latest comment for the template.

### PR DESCRIPTION
**Pull request by favonia**
Close #197.

### CODE REVIEW

**Comment by favonia** [comment]
So the checker is essentially working, but it is a bit slow. To make things work, a few architectural changes should help.

**Comment by favonia** [comment]
Current progress:
- `axiom.cooltt`: okay.
- `base-types.cooltt`: okay.
- `circle.cooltt`: okay if `45` is changed to a very small number.
- `com.cooltt`: okay.
- `elab.cooltt`: okay.
-  `evan.cooltt`: okay.
- `groupoid-laws`: **too slow.**
- `hcom-type.cooltt`: okay.
- `hlevel.cooltt`: **not working** because of the lack of left-inverting (that is, too weak when joins appear on the LHS):
  ```
  test/hlevel.cooltt:62.13-62.29 [Error]:
    Expected A/prop a {q j} k = A/prop a {p j} k : A
  ```
- `iso.cooltt`: okay.
- `nat-path.cooltt`: **not working.**
  ```
  test/nat-path.cooltt:61.25-61.33 [Error]:
    Expected trans/filler A {_x₅ => p 0} {_x₅ => p _x₅} j l =
             trans/filler A {_x₅ => p 0} {_x₅ => p _x₅} i l
             : A
  ```
- `path-types.cooltt`: okay
- `selfification.cooltt`: okay
- `v.cooltt`: okay

**Comment by favonia** [comment]
Progress: I tried various engineering tricks and the current "classical" solver seems to be the fastest (if Z3 is used). The ad-hoc solver is still the fastest.

**Comment by favonia** [comment]
With primitive left-inverting, the new solver can pass all cases, but CI takes forever (~15 mins) to install the z3 package. @TOTBWF volunteered to take a look.

**Comment by favonia** [comment]
@TOTBWF I proposed reverting all the changes to the GitHub Actions in this branch.

**Comment by favonia** [comment]
Bad news: a fresh build with the new Docker CI introduced in #265 would take ~45mins.
Good news: cache is working, so subsequent builds should be fast.

@TOTBWF @jonsterling I wonder how you feel about the 45-min cost that we occasionally have to pay...

**Comment by jonsterling** [comment]
Personally I don't mind if every once in a while, we have to do a totally fresh build and it takes forever. Correct me if I'm wrong, but it sounds like this would not happy too frequently during ordinary development. Right?

**Comment by favonia** [comment]
> Personally I don't mind if every once in a while, we have to do a totally fresh build and it takes forever. Correct me if I'm wrong, but it sounds like this would not happy too frequently during ordinary development. Right?

Correct, and there are more engineering tricks to work around it if the situation becomes dire.

**Comment by favonia** [comment]
I'm no longer interested in maintaining the z3 solver.

**Pull request closed without merging**
